### ISSUE TITLE
problems running batchy.py

### ISSUE THREAD

**Issue by Cubbun** [rwnull/HCRProbeMakerCL#2]
Dear rwnull,

I cloned your HCR probe maker and wanted to run it with multiple samples. 
`python3 ./batch.py -amp b1,b2 -batch TRP_contigs.fasta -max 30
`

My system:
Ubuntu 22.04.4 LTS

There are a few issues arising:

1.  In the OLOGO folder, the Name column of all files is wrong: B1_contigNr_A1 should be B1_contig_Nr_A1
**Solution:** in output.py I changed line89 + line90 
from:
`yname1 = str(amplifier+'-'+name+count+'_'+str(a+1)+'A')`
`yname2 = str(amplifier+'-'+name+count+'_'+str(a+1)+'B')`
to:
`yname1 = str(amplifier+'-'+name+'_'+count+'_'+str(a+1)+'A')`
`yname2 = str(amplifier+'-'+name+'_'+count+'_'+str(a+1)+'B')`

2. The batch.py file does not run and gives me the error: 
[AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?]
**Solution:** in batchy.py change line36
from:
`pdf=pdf.append({"file":filename2,"id":name,"seq":seq,"amp":amp,"GC":gc,"gcr":polyCG,"atr":polyAT,"delay":pause,"blast":txptome,"maxnum":maxprobes},ignore_index=True)` 
to:
`pdf=pdf._append({"file":filename2,"id":name,"seq":seq,"amp":amp,"GC":gc,"gcr":polyCG,"atr":polyAT,"delay":pause,"blast":txptome,"maxnum":maxprobes},ignore_index=True)` 

3. batch.py is giving for each contig-amplifier combination only one output:
TRPa_B1
TRPb_B2
TRPc_B1
TRPd_B2
...
**Solution:** I added an additional for loop in line27 (indenting all thereafter until line 46)
`for i in range(len(amplifier)): `
and remove line39 - line42 

4. The batchy.py does not work for only one amplifier:
Replace line31 with
`if (isinstance(amplifier, list)): `
`    amp = str(amplifier[j])`
`else:`
`    amp=str(amplifier)`

My version is attached.
**[HCRProbeMaker.zip](https://github.com/user-attachments/files/15833232/HCRProbeMaker.zip)** 

If there is an easier solution please let me know

Kind regards,
David Hug

**Comment by rwnull** [comment]
Hey David,
Thanks for your kind bug hunting and squashing! I have been working on making some of these same issues myself and am planning to push the update soon.

Thanks!

**Comment by Cubbun** [comment]
Thank you. I like the tool and plan on using it for further experiments.
